/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.trabajopractico6;

import Entidades.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Giulietta
 */
public class VistaEliminarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaEliminarCliente
     */
    public VistaEliminarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LTelefono = new javax.swing.JLabel();
        LDNI = new javax.swing.JLabel();
        LApellido = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LCiudad = new javax.swing.JLabel();
        TTelefono = new javax.swing.JTextField();
        TDNI = new javax.swing.JTextField();
        TApellido = new javax.swing.JTextField();
        TNombre = new javax.swing.JTextField();
        TCiudad = new javax.swing.JTextField();
        BBuscar = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Eliminar Cliente");

        LTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LTelefono.setText("Teléfono");

        LDNI.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LDNI.setText("DNI");

        LApellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LApellido.setText("Apellido");

        LNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LNombre.setText("Nombre");

        LCiudad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        LCiudad.setText("Ciudad");

        TTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTelefonoActionPerformed(evt);
            }
        });

        TDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TDNIActionPerformed(evt);
            }
        });

        BBuscar.setText("Buscar");
        BBuscar.setMaximumSize(new java.awt.Dimension(581, 518));
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTelefono)
                            .addComponent(LDNI)
                            .addComponent(LApellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNombre)
                            .addComponent(LCiudad))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TTelefono)
                    .addComponent(TDNI)
                    .addComponent(TApellido)
                    .addComponent(TNombre)
                    .addComponent(TCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BEliminar)
                .addGap(26, 26, 26)
                .addComponent(BSalir)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTelefono)
                    .addComponent(TTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDNI)
                    .addComponent(TDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellido)
                    .addComponent(TApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCiudad)
                    .addComponent(TCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSalir)
                    .addComponent(BEliminar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTelefonoActionPerformed

    private void TDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TDNIActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Long telefono1 = Long.parseLong(TTelefono.getText());
            Cliente c = new Cliente();
        c = Menu.miDirectorio.buscarCliente(telefono1);
        if (c==null){
            JOptionPane.showMessageDialog(this, "No se encontró al cliente");
        } else {
            TDNI.setText(c.getDni()+"");
            TApellido.setText(c.getApellido());
            TNombre.setText(c.getNombre());
            TCiudad.setText(c.getCiudad());
        }
        } catch(Exception ca){
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        }
    }//GEN-LAST:event_BBuscarActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        // TODO add your handling code here:
        Menu.miDirectorio.borrarCliente(Long.parseLong(TTelefono.getText()));
        JOptionPane.showMessageDialog(this, "Cliente eliminado");
        limpiar();
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed
    private void limpiar(){
        TNombre.setText("");
        TApellido.setText("");
        TDNI.setText("");
        TCiudad.setText("");
        TTelefono.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LCiudad;
    private javax.swing.JLabel LDNI;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LTelefono;
    private javax.swing.JTextField TApellido;
    private javax.swing.JTextField TCiudad;
    private javax.swing.JTextField TDNI;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TTelefono;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
